[env]
platform = espressif32
board = seeed_xiao_esp32s3
framework = espidf
board_build.f_cpu = 240000000L
board_build.partitions = partitions.csv
monitor_speed = 115200
upload_speed = 921600
build_unflags =
  -Werror
  -Werror=all
board_build.cmake_extra_args =
  -DSDKCONFIG_DEFAULTS=sdkconfig.defaults
monitor_filters = esp32_exception_decoder

[env:seeed_xiao_esp32s3]
build_flags =
  -DZCCI_COMPARISON_MODE_GATED_BUILD=1
  -DZCCI_FRAME_SCHEDULE_DELAY_UNTIL_BUILD=1

[env:seeed_xiao_esp32s3_gated]
build_flags =
  -DZCCI_COMPARISON_MODE_GATED_BUILD=1
  -DZCCI_FRAME_SCHEDULE_DELAY_UNTIL_BUILD=1

[env:seeed_xiao_esp32s3_always_on]
build_flags =
  -DZCCI_COMPARISON_MODE_ALWAYS_ON_BUILD=1
  -DZCCI_FRAME_SCHEDULE_DELAY_UNTIL_BUILD=1

[env:seeed_xiao_esp32s3_gated_schedule_disabled]
build_flags =
  -DZCCI_COMPARISON_MODE_GATED_BUILD=1
  -DZCCI_FRAME_SCHEDULE_DISABLED_BUILD=1

[env:seeed_xiao_esp32s3_always_on_schedule_disabled]
build_flags =
  -DZCCI_COMPARISON_MODE_ALWAYS_ON_BUILD=1
  -DZCCI_FRAME_SCHEDULE_DISABLED_BUILD=1
